### ISSUE TITLE
Class not find issue

### ISSUE THREAD

**Issue by shiv71** [sjthn/FbLithoDemo#1]
ProgressBar,ListItem class not find in MainActivity

**Comment by sjthn** [comment]
Hey! The ListItem and ProgressBar are generated at compile time. Please look at the [ListItemSpec](https://github.com/sjthn/FbLithoDemo/blob/master/app/src/main/java/com/example/srijith/fblithodemo/ListItemSpec.java) and [ProgressBarSpec](https://github.com/sjthn/FbLithoDemo/blob/master/app/src/main/java/com/example/srijith/fblithodemo/ProgressBarSpec.java) classes. Litho generates the desired component from the Spec class which it identifies at compile time using the `@LayoutSpec` annotation.

You can read my blog here for more info https://medium.com/@srijithn/getting-started-with-facebook-litho-1c29a281205b
